"""
Django settings for GestorIT project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3llh5tla!(gfx$b=cw4*wpd@z29#(i1f0x1&!e2n+7joxetub)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'GestorApp.apps.GestorappConfig',
    'django_bootstrap5',
    'django_q',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GestorIT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Templates'], # Carpeta templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'GestorApp.context_processors.roles',
                'GestorApp.context_processors.breadcrumbs',
                'GestorApp.context_processors.nav_badges',
            ],
        },
    },
]

WSGI_APPLICATION = 'GestorIT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


# Usuario y contraseña de la base de datos PostgreSQL. Cambiar para mayor seguridad.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'GestorIT',
        'USER': 'Admin',
        'PASSWORD': '12345678',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Tijuana'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Limites y reglas de subida (imagenes, PDF, plantillas).
MEDIA_UPLOAD = {
    "image_max_bytes": 5 * 1024 * 1024,       # 5 MB
    "pdf_max_bytes": 10 * 1024 * 1024,        # 10 MB
    "plantilla_max_bytes": 15 * 1024 * 1024,  # 15 MB
    "image_extensions": (".jpg", ".jpeg", ".png", ".gif", ".webp"),
    "plantilla_extensions": (".docx", ".xlsx", ".pdf"),
}
# Tope global de Django alineado al archivo mas grande permitido.
DATA_UPLOAD_MAX_MEMORY_SIZE = MEDIA_UPLOAD["plantilla_max_bytes"]
FILE_UPLOAD_MAX_MEMORY_SIZE = MEDIA_UPLOAD["plantilla_max_bytes"]

# Adds an asterisk next to required fields and a highlight on fields with
# errors, rendered through django-bootstrap5 on every form in the app.
BOOTSTRAP5 = {
    "required_css_class": "field-required",
    "error_css_class": "field-error",
}

# Cache de KPIs / badges (sidebar + home). TTL corto para no saturar la BD.
METRICS_CACHE_TTL = 45  # segundos
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "gestor-it-metrics",
        "TIMEOUT": METRICS_CACHE_TTL,
        "OPTIONS": {"MAX_ENTRIES": 2000},
    }
}

# Jobs en background (django-q2, broker ORM = PostgreSQL, sin Redis).
# Arrancar worker: python manage.py qcluster
# Schedules: retencion diaria + recordatorios operativos cada 15 min.
BACKGROUND_JOBS_ENABLED = True
# True = siempre ejecuta en el request (util en dev sin worker).
BACKGROUND_JOBS_SYNC = False
Q_CLUSTER = {
    "name": "gestorit",
    "workers": 2,
    "recycle": 500,
    "timeout": 300,
    "retry": 360,
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
    "catch_up": False,
}

# Politica de retencion del historial general de actividad.
# Flujo default: activo -> archivado (oculto) -> purgado (borrado).
# Ejecutar periodicamente: python manage.py limpiar_historial
# Vista previa sin cambios: python manage.py limpiar_historial --dry-run
# Encolar: python manage.py limpiar_historial --async
HISTORIAL_RETENCION = {
    # archivar_luego_purgar | solo_archivar | solo_purgar
    "modo": "archivar_luego_purgar",
    # Dias que un evento permanece visible (activo) antes de archivarse.
    "dias_activo": 180,
    # Dias adicionales en archivo antes de borrarlo de la base de datos.
    # Solo aplica en modo archivar_luego_purgar.
    "dias_archivo": 365,
    # Si True, los eventos de nivel "critico" no se archivan ni se purgan.
    "proteger_criticos": True,
}

# Auth redirects
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
