# Generated by Django 6.0.4 on 2026-05-04 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=100)),
                ('descripcion_area', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_bitacora', models.CharField(max_length=30, unique=True)),
                ('fecha_bitacora', models.DateTimeField(default=django.utils.timezone.now)),
                ('situacion', models.CharField(max_length=180)),
                ('descripcion_situacion', models.TextField()),
            ],
            options={
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacora',
            },
        ),
        migrations.CreateModel(
            name='CategoriaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion_categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompraMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_compra', models.CharField(max_length=30, unique=True)),
                ('fecha_compra', models.DateField()),
                ('solicitado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_compra', models.CharField(default='Solicitada', max_length=30)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_edificio', models.CharField(max_length=100)),
                ('descripcion_edificio', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_presupuesto', models.CharField(max_length=30, unique=True)),
                ('fecha_presupuesto', models.DateField()),
                ('cliente_o_area', models.CharField(max_length=150)),
                ('elaborado_por', models.CharField(max_length=150)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_presupuesto', models.CharField(default='Borrador', max_length=30)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=150)),
                ('contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_puesto', models.CharField(max_length=100)),
                ('descripcion_puesto', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_answer', models.CharField(max_length=30)),
                ('fecha_answer', models.DateTimeField(default=django.utils.timezone.now)),
                ('solucion', models.CharField(max_length=180)),
                ('descripcion_solucion', models.TextField()),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='GestorApp.bitacora')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answer',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompraMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='GestorApp.compramaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('marca', models.CharField(blank=True, max_length=80, null=True)),
                ('modelo', models.CharField(blank=True, max_length=80, null=True)),
                ('descripcion_equipo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('costo_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('garantia_meses', models.IntegerField(default=0)),
                ('estado_equipo', models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado'), ('En Mantenimiento', 'En Mantenimiento'), ('Baja', 'Baja')], default='Disponible', max_length=30)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestorApp.categoriaequipo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorApp.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo'), ('Predictivo', 'Predictivo')], max_length=20)),
                ('estado_mantenimiento', models.CharField(choices=[('Programado', 'Programado'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Programado', max_length=20)),
                ('fecha_programada', models.DateField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tecnico_responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('costo_mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descripcion_falla', models.CharField(blank=True, max_length=255, null=True)),
                ('acciones_realizadas', models.TextField(blank=True, null=True)),
                ('proxima_fecha_mantenimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='GestorApp.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recordatorio', models.DateTimeField()),
                ('canal_recordatorio', models.CharField(blank=True, max_length=50, null=True)),
                ('enviado', models.BooleanField(default=False)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='GestorApp.mantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleado', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorApp.area')),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorApp.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Transferencia', 'Transferencia'), ('Baja', 'Baja')], max_length=20)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('origen', models.CharField(blank=True, max_length=150, null=True)),
                ('destino', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='GestorApp.equipo')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorApp.personal')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estado_asignacion', models.CharField(choices=[('Activa', 'Activa'), ('Devuelta', 'Devuelta'), ('Extraviada', 'Extraviada')], default='Activa', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='GestorApp.equipo')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_asignados', to='GestorApp.personal')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='GestorApp.presupuesto')),
            ],
        ),
        migrations.AddField(
            model_name='compramaterial',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorApp.proveedor'),
        ),
        migrations.CreateModel(
            name='TicketIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_ticket', models.CharField(max_length=30, unique=True)),
                ('fecha_support', models.DateTimeField(default=django.utils.timezone.now)),
                ('requerimiento', models.CharField(default='', max_length=180)),
                ('tipo_ticket', models.CharField(choices=[('ADMINISTRACION', 'ADMINISTRACION'), ('BPCS', 'BPCS'), ('HARDWARE', 'HARDWARE'), ('HELPDESK', 'HELPDESK'), ('TELEFONIA', 'TELEFONIA'), ('SOFTWARE', 'SOFTWARE')], default='HELPDESK', max_length=30)),
                ('sub_tipo_ticket', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_equipo', models.CharField(choices=[('Computadora', 'Computadora'), ('Laptop', 'Laptop'), ('Impresora', 'Impresora'), ('Telefono', 'Telefono'), ('Escaner', 'Escaner'), ('Tablet', 'Tablet'), ('Otro', 'Otro')], default='Computadora', max_length=20)),
                ('otro_tipo_equipo', models.CharField(blank=True, max_length=120, null=True)),
                ('identificador_reporte', models.CharField(blank=True, max_length=80, null=True, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField()),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Abierto', 'Abierto'), ('En Revision', 'En Revision'), ('En Proceso', 'En Proceso'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_support', to='GestorApp.area')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorApp.equipo')),
            ],
            options={
                'verbose_name': 'Support',
                'verbose_name_plural': 'Support',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_check', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_check', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(default='', max_length=150)),
                ('solucion', models.TextField(default='')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('ya_terminado', models.BooleanField(default=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_check', to='GestorApp.ticketit')),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Check',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasillo', models.CharField(blank=True, max_length=50, null=True)),
                ('rack', models.CharField(blank=True, max_length=50, null=True)),
                ('anaquel', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestorApp.edificio')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorApp.ubicacion'),
        ),
        migrations.CreateModel(
            name='ZonaEdificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=100)),
                ('descripcion_zona', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='GestorApp.edificio')),
            ],
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestorApp.zonaedificio'),
        ),
    ]
