# Generated by Django 6.0.4 on 2026-05-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GestorApp", "0003_ticketit_solicitado_por"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketit",
            name="prioridad",
            field=models.CharField(
                choices=[
                    ("Baja", "Baja"),
                    ("Media", "Media"),
                    ("Alta", "Alta"),
                    ("Urgente", "Urgente"),
                ],
                default="Media",
                max_length=10,
            ),
        ),
    ]
