# Generated by Django 6.0.4 on 2026-05-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GestorApp", "0015_seguimientoticket_usuario_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipo",
            name="costo_compra",
        ),
        migrations.RemoveField(
            model_name="equipo",
            name="fecha_compra",
        ),
        migrations.RemoveField(
            model_name="equipo",
            name="garantia_meses",
        ),
    ]
