# Generated by Django 6.0.4 on 2026-05-25 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0017_ticketit_area_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketit',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_support', to='GestorApp.area', verbose_name='Area'),
        ),
    ]
