# Generated by Django 6.0.6 on 2026-07-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0022_remove_ubicacion_anaquel_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='num_Pedimiento',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
