# Generated by Django 6.0.6 on 2026-07-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0023_equipo_num_pedimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='num_Pedimiento',
            new_name='Numero_Pedimiento',
        ),
    ]
