# Generated by Django 6.0.6 on 2026-07-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0025_alter_seguimientoticket_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientoticket',
            name='avance_realizado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguimientoticket',
            name='fecha_proximo_seguimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguimientoticket',
            name='pendiente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguimientoticket',
            name='proximo_paso',
            field=models.TextField(blank=True, null=True),
        ),
    ]
