# Generated by Django 6.0.7 on 2026-07-22 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0026_seguimientoticket_avance_realizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_archivo', models.CharField(choices=[('DOCX', 'Word (.docx)'), ('XLSX', 'Excel (.xlsx)'), ('PDF', 'PDF')], max_length=10)),
                ('archivo', models.FileField(upload_to='plantillas_orden_compra')),
                ('campos', models.JSONField(blank=True, default=list)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='orden_compra_valores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='orden_compra_plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='GestorApp.plantilladocumento'),
        ),
    ]
