# Generated by Django 6.0.4 on 2026-05-06 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GestorApp", "0002_ticketit_tipo_equipo_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketit",
            name="solicitado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_support_solicitados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Solicitado por",
            ),
        ),
    ]
