# Generated by Django 6.0.4 on 2026-05-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0010_remove_compra_material_totals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compramaterial',
            name='estado_compra',
            field=models.CharField(choices=[('Solicitada', 'Solicitada'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado'), ('Cancelada', 'Cancelada')], default='Solicitada', max_length=30),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='estado_presupuesto',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado'), ('Cancelado', 'Cancelado')], default='Borrador', max_length=30),
        ),
    ]
