# Generated by Django 6.0.4 on 2026-05-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0013_compramaterial_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketit',
            name='identificador_reporte',
        ),
    ]
