# Generated by Django 6.0.4 on 2026-05-25 00:00

from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    SeguimientoTicket = apps.get_model("GestorApp", "SeguimientoTicket")
    user_model = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    username_field = getattr(user_model, "USERNAME_FIELD", "username")
    has_email = any(field.name == "email" for field in user_model._meta.fields)

    for seguimiento in (
        SeguimientoTicket.objects.exclude(usuario__isnull=True).exclude(usuario__exact="")
    ):
        raw_value = (seguimiento.usuario or "").strip()
        if not raw_value:
            continue
        user = user_model.objects.filter(
            **{f"{username_field}__iexact": raw_value}
        ).first()
        if not user and has_email and "@" in raw_value:
            user = user_model.objects.filter(email__iexact=raw_value).first()
        if user:
            seguimiento.usuario_user = user
            seguimiento.save(update_fields=["usuario_user"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("GestorApp", "0014_remove_ticketit_identificador_reporte"),
    ]

    operations = [
        migrations.AddField(
            model_name="seguimientoticket",
            name="usuario_user",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET_NULL,
                related_name="checks_resueltos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="seguimientoticket",
            name="usuario",
        ),
        migrations.RenameField(
            model_name="seguimientoticket",
            old_name="usuario_user",
            new_name="usuario",
        ),
    ]
