# Generated by Django 6.0.4 on 2026-05-25 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GestorApp", "0016_remove_equipo_campos_compra"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticketit",
            old_name="departamento",
            new_name="area",
        ),
        migrations.AddField(
            model_name="ticketit",
            name="puesto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_support_puesto",
                to="GestorApp.puesto",
                verbose_name="Puesto",
            ),
        ),
    ]
