# Generated by Django 6.0.4 on 2026-05-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0018_alter_ticketit_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoequipo',
            name='cantidad',
        ),
    ]
