# Generated by Django 6.0.4 on 2026-05-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0019_remove_movimientoequipo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoequipo',
            name='tipo_movimiento',
            field=models.CharField(choices=[('Dada de alta', 'Dada de alta'), ('Dada de baja', 'Dada de baja'), ('Asignacion de equipo', 'Asignacion de equipo'), ('Cambio de asignacion', 'Cambio de asignacion'), ('En mantenimiento', 'En mantenimiento'), ('Cambio de ubicacion', 'Cambio de ubicacion')], max_length=20),
        ),
    ]
