# Generated by Django 6.0.4 on 2026-05-26 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0020_alter_movimientoequipo_tipo_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamantenimiento',
            name='canal_recordatorio',
        ),
        migrations.RemoveField(
            model_name='agendamantenimiento',
            name='enviado',
        ),
        migrations.RemoveField(
            model_name='agendamantenimiento',
            name='fecha_recordatorio',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='acciones_realizadas',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='proxima_fecha_mantenimiento',
        ),
        migrations.AddField(
            model_name='agendamantenimiento',
            name='acciones_realizadas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamantenimiento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamantenimiento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamantenimiento',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agendamantenimiento',
            name='proxima_fecha_mantenimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamantenimiento',
            name='mantenimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cierre', to='GestorApp.mantenimiento'),
        ),
    ]
