# Generated by Django 6.0.4 on 2026-06-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GestorApp", "0021_remove_agendamantenimiento_canal_recordatorio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ubicacion",
            name="anaquel",
        ),
        migrations.RemoveField(
            model_name="ubicacion",
            name="rack",
        ),
    ]
