# Generated by Django 6.0.6 on 2026-07-15 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0024_rename_num_pedimiento_equipo_numero_pedimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientoticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='GestorApp.ticketit'),
        ),
        migrations.AlterField(
            model_name='seguimientoticket',
            name='ya_terminado',
            field=models.BooleanField(default=False),
        ),
    ]
