# Generated by Django 6.0.7 on 2026-07-27 03:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _importar_movimientos_equipo(apps, schema_editor):
    MovimientoEquipo = apps.get_model("GestorApp", "MovimientoEquipo")
    HistorialActividad = apps.get_model("GestorApp", "HistorialActividad")
    registros = []
    for movimiento in MovimientoEquipo.objects.select_related("equipo").iterator():
        equipo = movimiento.equipo
        registros.append(
            HistorialActividad(
                fecha=movimiento.fecha_movimiento,
                modulo="movimiento_equipo",
                accion="otro",
                titulo=f"{movimiento.tipo_movimiento}: {equipo}",
                descripcion=movimiento.observaciones or "",
                objeto_tipo="GestorApp.movimientoequipo",
                objeto_id=movimiento.pk,
                objeto_etiqueta=str(equipo),
                enlace_nombre="movimientoequipo_update",
                enlace_pk=movimiento.pk,
                metadata={
                    "tipo_movimiento": movimiento.tipo_movimiento,
                    "origen": movimiento.origen,
                    "destino": movimiento.destino,
                    "importado": True,
                },
            )
        )
    if registros:
        HistorialActividad.objects.bulk_create(registros, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0028_ordencompra_unificada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modulo', models.CharField(choices=[('ticket', 'Tickets de soporte'), ('seguimiento', 'Seguimiento de tickets'), ('equipo', 'Equipos'), ('asignacion', 'Asignaciones de equipo'), ('movimiento_equipo', 'Movimientos de equipo'), ('personal', 'Personal'), ('mantenimiento', 'Mantenimiento'), ('orden_compra', 'Ordenes de compra'), ('bitacora', 'Bitacora'), ('sistema', 'Sistema')], db_index=True, max_length=32)),
                ('accion', models.CharField(choices=[('creacion', 'Creacion'), ('actualizacion', 'Actualizacion'), ('eliminacion', 'Eliminacion'), ('cambio_estado', 'Cambio de estado'), ('asignacion', 'Asignacion'), ('devolucion', 'Devolucion'), ('otro', 'Otro')], db_index=True, max_length=24)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('objeto_tipo', models.CharField(blank=True, max_length=80)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('objeto_etiqueta', models.CharField(blank=True, max_length=180)),
                ('enlace_nombre', models.CharField(blank=True, max_length=80)),
                ('enlace_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de actividad',
                'verbose_name_plural': 'Historial de actividades',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.RunPython(_importar_movimientos_equipo, migrations.RunPython.noop),
    ]
