# Generated by Django 6.0.7 on 2026-07-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0029_historial_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialactividad',
            name='archivado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historialactividad',
            name='entidad_relacionada_etiqueta',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='historialactividad',
            name='entidad_relacionada_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialactividad',
            name='entidad_relacionada_tipo',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='historialactividad',
            name='es_automatico',
            field=models.BooleanField(db_index=True, default=False, help_text='True si lo genero el sistema (ej. movimiento al dar de alta un equipo).'),
        ),
        migrations.AddField(
            model_name='historialactividad',
            name='fecha_archivado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialactividad',
            name='nivel',
            field=models.CharField(choices=[('info', 'Informativo'), ('advertencia', 'Advertencia'), ('critico', 'Critico')], db_index=True, default='info', max_length=16),
        ),
    ]
