# Generated by Django 6.0.6 on 2026-07-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0032_roles_groups_y_tipo_mantenimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre_proveedor'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Codigo interno'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Codigo postal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='notas',
            field=models.TextField(blank=True, help_text='Condiciones de pago, garantia, observaciones, etc.', null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='sitio_web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Mantenimiento', 'Mantenimiento'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Consumibles', 'Consumibles'), ('Otro', 'Otro')], max_length=30, null=True, verbose_name='Tipo de proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(max_length=150, verbose_name='Nombre comercial'),
        ),
    ]
