# Generated by Django 6.0.6 on 2026-08-04 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0034_proveedor_codigo_interno_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='detalle_orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='GestorApp.detalleordencompra', verbose_name='Linea de orden'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='GestorApp.ordencompra', verbose_name='Orden de compra'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='origen_alta',
            field=models.CharField(choices=[('Compra', 'Compra (con OC)'), ('Legado', 'Legado / historico'), ('Donacion', 'Donacion'), ('Transferencia', 'Transferencia'), ('Otro', 'Otro')], default='Legado', max_length=20, verbose_name='Origen de alta'),
        ),
    ]
