# Generated by Django 6.0.6 on 2026-08-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0035_equipo_origen_orden_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado_equipo',
            field=models.CharField(choices=[('En Stock', 'En Stock'), ('Asignado', 'Asignado'), ('En Mantenimiento', 'En Mantenimiento'), ('Baja', 'Baja')], default='En Stock', max_length=30),
        ),
    ]
