# Generated by Django 6.0.6 on 2026-08-10 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0036_alter_equipo_estado_equipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialactividad',
            name='modulo',
            field=models.CharField(choices=[('ticket', 'Tickets de soporte'), ('seguimiento', 'Seguimiento de tickets'), ('equipo', 'Equipos'), ('asignacion', 'Asignaciones de equipo'), ('movimiento_equipo', 'Movimientos de equipo'), ('personal', 'Personal'), ('mantenimiento', 'Mantenimiento'), ('orden_compra', 'Ordenes de compra'), ('bitacora', 'Bitacora'), ('sistema', 'Sistema'), ('gobierno', 'Gobierno y roles'), ('solicitud_equipo', 'Solicitudes de equipo')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='CoberturaTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ausente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas_como_ausente', to=settings.AUTH_USER_MODEL, verbose_name='Tecnico ausente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coberturas_creadas', to=settings.AUTH_USER_MODEL)),
                ('suplente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas_como_suplente', to=settings.AUTH_USER_MODEL, verbose_name='Suplente')),
            ],
            options={
                'verbose_name': 'Cobertura de tickets',
                'verbose_name_plural': 'Coberturas de tickets',
                'ordering': ['-fecha_inicio', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=160)),
                ('justificacion', models.TextField()),
                ('urgencia', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En revision', 'En revision'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], db_index=True, default='Pendiente', max_length=20)),
                ('notas_solicitante', models.CharField(blank=True, max_length=255)),
                ('notas_it', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='GestorApp.categoriaequipo')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_origen', to='GestorApp.equipo')),
                ('personal', models.ForeignKey(blank=True, help_text='Perfil de personal a quien se asignaria el equipo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_equipo', to='GestorApp.personal')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_equipo_revisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_equipo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de equipo',
                'verbose_name_plural': 'Solicitudes de equipo',
                'ordering': ['-fecha_creacion', '-pk'],
            },
        ),
    ]
