# Generated by Django 6.0.6 on 2026-08-10 17:10

import GestorApp.media_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0037_gobierno_cobertura_solicitud_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=GestorApp.media_security.SafeUploadTo('equipos')),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to=GestorApp.media_security.SafeUploadTo('ordenes_compra')),
        ),
        migrations.AlterField(
            model_name='plantilladocumento',
            name='archivo',
            field=models.FileField(upload_to=GestorApp.media_security.SafeUploadTo('plantillas_orden_compra')),
        ),
        migrations.AlterField(
            model_name='ticketit',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=GestorApp.media_security.SafeUploadTo('support')),
        ),
    ]
