# Generated by Django 6.0.6 on 2026-08-18 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0038_media_upload_safe_paths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoSolicitudEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_check', models.DateTimeField(default=django.utils.timezone.now)),
                ('avance_realizado', models.TextField(blank=True, null=True)),
                ('pendiente', models.TextField(blank=True, null=True)),
                ('proximo_paso', models.TextField(blank=True, null=True)),
                ('fecha_proximo_seguimiento', models.DateField(blank=True, null=True)),
                ('solucion', models.TextField(blank=True, default='')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('ya_terminado', models.BooleanField(default=False)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='GestorApp.solicitudequipo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_solicitud_equipo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de solicitud',
                'verbose_name_plural': 'Seguimientos de solicitud',
                'ordering': ['-fecha_check', '-pk'],
            },
        ),
    ]
