# Generated by Django 6.0.6 on 2026-08-18 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0039_seguimientosolicitudequipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-fecha_answer', '-pk'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answer'},
        ),
        migrations.AlterModelOptions(
            name='bitacora',
            options={'ordering': ['-fecha_bitacora', '-pk'], 'verbose_name': 'Bitacora', 'verbose_name_plural': 'Bitacora'},
        ),
        migrations.AddField(
            model_name='answer',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers_bitacora', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='folio_answer',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='folio_bitacora',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
