# Generated by Django 6.0.6 on 2026-08-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0040_bitacora_answer_usuario_folio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimientosolicitudequipo',
            options={'ordering': ['-fecha_check', '-pk'], 'verbose_name': 'Revision IT', 'verbose_name_plural': 'Revisiones IT'},
        ),
    ]
