# Generated by Django 6.0.6 on 2026-08-25 17:04

import GestorApp.media_security
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0041_alter_seguimientosolicitudequipo_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True)),
                ('es_interno', models.BooleanField(default=False, help_text='True si lo publico un tecnico o administrador.')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_ticket', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='GestorApp.ticketit')),
            ],
            options={
                'verbose_name': 'Comentario de ticket',
                'verbose_name_plural': 'Comentarios de ticket',
                'ordering': ['fecha', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTicketAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=GestorApp.media_security.SafeUploadTo('support/comentarios'))),
                ('nombre_original', models.CharField(blank=True, max_length=180)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='GestorApp.comentarioticket')),
            ],
            options={
                'verbose_name': 'Adjunto de comentario',
                'verbose_name_plural': 'Adjuntos de comentario',
                'ordering': ['pk'],
            },
        ),
    ]
