# Generated by Django 6.0.6 on 2026-09-02 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0047_ubicacion_es_stock_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='tag_1',
            field=models.CharField(blank=True, help_text='Opcional. Exactamente 6 digitos.', max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Tag 1 debe tener exactamente 6 digitos.', regex='^\\d{6}$')], verbose_name='Tag 1'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tag_2',
            field=models.CharField(blank=True, help_text='Opcional. Exactamente 4 digitos.', max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Tag 2 debe tener exactamente 4 digitos.', regex='^\\d{4}$')], verbose_name='Tag 2'),
        ),
    ]
