# Generated by Django 6.0.7 on 2026-09-09

from django.db import migrations, models
from django.utils import timezone


def cerrar_asignaciones_activas_duplicadas(apps, schema_editor):
    AsignacionEquipo = apps.get_model("GestorApp", "AsignacionEquipo")
    from django.db.models import Count

    duplicados = (
        AsignacionEquipo.objects.filter(estado_asignacion="Activa")
        .values("equipo_id")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    now = timezone.now()
    for fila in duplicados:
        qs = AsignacionEquipo.objects.filter(
            equipo_id=fila["equipo_id"],
            estado_asignacion="Activa",
        ).order_by("-fecha_asignacion", "-pk")
        keep = qs.first()
        if keep is None:
            continue
        qs.exclude(pk=keep.pk).update(
            estado_asignacion="Devuelta",
            fecha_devolucion=now,
        )


def reescribir_estado_disponible(apps, schema_editor):
    Equipo = apps.get_model("GestorApp", "Equipo")
    Equipo.objects.filter(estado_equipo="Disponible").update(estado_equipo="En Stock")


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("GestorApp", "0048_equipo_tag_1_tag_2"),
    ]

    operations = [
        migrations.RunPython(cerrar_asignaciones_activas_duplicadas, noop),
        migrations.RunPython(reescribir_estado_disponible, noop),
        migrations.AddConstraint(
            model_name="asignacionequipo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado_asignacion", "Activa")),
                fields=("equipo",),
                name="uniq_asignacion_activa_por_equipo",
            ),
        ),
    ]
