# Generated by Django 6.0.7 on 2026-09-09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("GestorApp", "0049_uniq_asignacion_activa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipo",
            name="fecha_alta",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="fecha",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.localdate,
                null=True,
            ),
        ),
    ]
