# Generated by Django 6.0.3 on 2026-04-14 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_user',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('assignable', models.BooleanField(default=True, help_text='Can this category be assigned to employees?')),
                ('requires_serial', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'db_table': 'asset_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'building',
                'ordering': ['site', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'manufacturer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'site',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Ticket Categories',
                'db_table': 'ticket_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=120)),
                ('default_maintenance_interval_days', models.IntegerField(blank=True, help_text='Default maintenance interval in days', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='GestorITapps.assetcategory')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='GestorITapps.manufacturer')),
            ],
            options={
                'db_table': 'asset_model',
                'ordering': ['manufacturer', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(blank=True, help_text='Physical asset tag', max_length=60, null=True, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('ASSIGNED', 'Assigned'), ('IN_REPAIR', 'In Repair'), ('RETIRED', 'Retired'), ('LOST', 'Lost')], default='IN_STOCK', max_length=20)),
                ('ownership', models.CharField(choices=[('OWNED', 'Owned'), ('RENTED', 'Rented'), ('VENDOR_OWNED', 'Vendor Owned')], default='OWNED', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='GestorITapps.assetcategory')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='GestorITapps.assetmodel')),
                ('current_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_building', to='GestorITapps.building')),
                ('current_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_site', to='GestorITapps.site')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='GestorITapps.vendor')),
            ],
            options={
                'db_table': 'asset',
                'ordering': ['asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=120, null=True)),
                ('job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees_building', to='GestorITapps.building')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='GestorITapps.appuser')),
                ('base_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees_site', to='GestorITapps.site')),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('condition_out', models.TextField(blank=True, help_text='Condition when assigned out', null=True)),
                ('condition_in', models.TextField(blank=True, help_text='Condition when returned', null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='GestorITapps.asset')),
                ('assigned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_made', to='GestorITapps.appuser')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to='GestorITapps.employee')),
            ],
            options={
                'db_table': 'asset_assignment',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('interval_days', models.IntegerField(help_text='Maintenance interval in days')),
                ('active', models.BooleanField(default=True)),
                ('applies_to_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans_category', to='GestorITapps.assetcategory')),
                ('applies_to_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans_model', to='GestorITapps.assetmodel')),
            ],
            options={
                'db_table': 'maintenance_plan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('actions_taken', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_orders', to='GestorITapps.asset')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='GestorITapps.maintenanceplan')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_work_orders', to='GestorITapps.vendor')),
            ],
            options={
                'db_table': 'maintenance_work_order',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='building',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='GestorITapps.site'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('WAITING_VENDOR', 'Waiting Vendor'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='GestorITapps.asset')),
                ('assigned_to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_assigned', to='GestorITapps.employee')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='GestorITapps.building')),
                ('requester_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_created', to='GestorITapps.employee')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='GestorITapps.site')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='GestorITapps.ticketcategory')),
            ],
            options={
                'db_table': 'ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestorITapps.employee')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='GestorITapps.ticket')),
            ],
            options={
                'db_table': 'ticket_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('floor', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='GestorITapps.building')),
            ],
            options={
                'db_table': 'zone',
                'ordering': ['building', 'code'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='GestorITapps.zone'),
        ),
        migrations.AddField(
            model_name='employee',
            name='base_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees_zone', to='GestorITapps.zone'),
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('RETURNED', 'Returned'), ('MOVED_LOCATION', 'Moved Location'), ('MAINTENANCE_CREATED', 'Maintenance Created'), ('MAINTENANCE_DONE', 'Maintenance Done'), ('STATUS_CHANGED', 'Status Changed'), ('OTHER', 'Other')], max_length=30)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='GestorITapps.asset')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_events_created', to='GestorITapps.appuser')),
                ('related_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='GestorITapps.assetassignment')),
                ('from_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_events_from', to='GestorITapps.employee')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_events_to', to='GestorITapps.employee')),
                ('related_mwo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='GestorITapps.maintenanceworkorder')),
                ('from_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_events_from_zone', to='GestorITapps.zone')),
                ('to_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_events_to_zone', to='GestorITapps.zone')),
            ],
            options={
                'db_table': 'asset_event',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='current_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_zone', to='GestorITapps.zone'),
        ),
        migrations.CreateModel(
            name='AssetSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_key', models.CharField(max_length=80)),
                ('spec_value', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='GestorITapps.asset')),
            ],
            options={
                'db_table': 'asset_specification',
                'unique_together': {('asset', 'spec_key')},
            },
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['employee'], name='asset_assig_employe_9f37c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetmodel',
            unique_together={('category', 'manufacturer', 'model_name')},
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('site', 'code')},
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorder',
            index=models.Index(fields=['asset', 'status'], name='maintenance_asset_i_991b89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('building', 'code')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority'], name='ticket_status_44874a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['requester_employee'], name='ticket_request_c25b13_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['asset'], name='ticket_asset_i_49f619_idx'),
        ),
        migrations.AddIndex(
            model_name='assetevent',
            index=models.Index(fields=['asset', 'occurred_at'], name='asset_event_asset_i_4f2d52_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='asset_status_289177_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['model'], name='asset_model_i_8c5b5c_idx'),
        ),
    ]
