# Generated by Django 6.0.3 on 2026-04-20 05:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorITapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recordatorio', models.DateTimeField()),
                ('canal_recordatorio', models.CharField(blank=True, max_length=50, null=True)),
                ('enviado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=100)),
                ('descripcion_area', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estado_asignacion', models.CharField(choices=[('Activa', 'Activa'), ('Devuelta', 'Devuelta'), ('Extraviada', 'Extraviada')], default='Activa', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion_categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompraMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_compra', models.CharField(max_length=30, unique=True)),
                ('fecha_compra', models.DateField()),
                ('solicitado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_compra', models.CharField(default='Solicitada', max_length=30)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompraMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_edificio', models.CharField(max_length=100)),
                ('descripcion_edificio', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('marca', models.CharField(blank=True, max_length=80, null=True)),
                ('modelo', models.CharField(blank=True, max_length=80, null=True)),
                ('descripcion_equipo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('costo_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('garantia_meses', models.IntegerField(default=0)),
                ('estado_equipo', models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado'), ('En Mantenimiento', 'En Mantenimiento'), ('Baja', 'Baja')], default='Disponible', max_length=30)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo'), ('Predictivo', 'Predictivo')], max_length=20)),
                ('estado_mantenimiento', models.CharField(choices=[('Programado', 'Programado'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Programado', max_length=20)),
                ('fecha_programada', models.DateField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tecnico_responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('costo_mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descripcion_falla', models.CharField(blank=True, max_length=255, null=True)),
                ('acciones_realizadas', models.TextField(blank=True, null=True)),
                ('proxima_fecha_mantenimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Transferencia', 'Transferencia'), ('Baja', 'Baja')], max_length=20)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('origen', models.CharField(blank=True, max_length=150, null=True)),
                ('destino', models.CharField(blank=True, max_length=150, null=True)),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleado', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_presupuesto', models.CharField(max_length=30, unique=True)),
                ('fecha_presupuesto', models.DateField()),
                ('cliente_o_area', models.CharField(max_length=150)),
                ('elaborado_por', models.CharField(max_length=150)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_presupuesto', models.CharField(default='Borrador', max_length=30)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=150)),
                ('contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_puesto', models.CharField(max_length=100)),
                ('descripcion_puesto', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('usuario_evento', models.CharField(max_length=150)),
                ('cambio_estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_ticket', models.CharField(max_length=30, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Crítica', 'Crítica')], default='Media', max_length=10)),
                ('estado_ticket', models.CharField(choices=[('Abierto', 'Abierto'), ('En Proceso', 'En Proceso'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20)),
                ('tecnico_asignado', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('solucion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasillo', models.CharField(blank=True, max_length=50, null=True)),
                ('rack', models.CharField(blank=True, max_length=50, null=True)),
                ('anaquel', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaEdificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=100)),
                ('descripcion_zona', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='asset_status_289177_idx',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='asset_model_i_8c5b5c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='assetspecification',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='assetspecification',
            name='asset',
        ),
        migrations.RemoveIndex(
            model_name='assetassignment',
            name='asset_assig_employe_9f37c8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='assetmodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='applies_to_category',
        ),
        migrations.RemoveIndex(
            model_name='assetevent',
            name='asset_event_asset_i_4f2d52_idx',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='applies_to_model',
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='building',
            name='site',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='building',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='base_building',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='base_site',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='base_zone',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='author_employee',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceworkorder',
            name='maintenance_asset_i_991b89_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticket_status_44874a_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticket_request_c25b13_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticket_asset_i_49f619_idx',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='ticket',
        ),
        migrations.AddField(
            model_name='detallecompramaterial',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='GestorITapps.compramaterial'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestorITapps.categoriaequipo'),
        ),
        migrations.AddField(
            model_name='asignacionequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='GestorITapps.equipo'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='GestorITapps.equipo'),
        ),
        migrations.AddField(
            model_name='agendamantenimiento',
            name='mantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='GestorITapps.mantenimiento'),
        ),
        migrations.AddField(
            model_name='movimientoequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='GestorITapps.equipo'),
        ),
        migrations.AddField(
            model_name='personal',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorITapps.area'),
        ),
        migrations.AddField(
            model_name='asignacionequipo',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_asignados', to='GestorITapps.personal'),
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='GestorITapps.presupuesto'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorITapps.proveedor'),
        ),
        migrations.AddField(
            model_name='compramaterial',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorITapps.proveedor'),
        ),
        migrations.AddField(
            model_name='personal',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorITapps.puesto'),
        ),
        migrations.AddField(
            model_name='ticketit',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorITapps.equipo'),
        ),
        migrations.AddField(
            model_name='ticketit',
            name='personal_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestorITapps.personal'),
        ),
        migrations.AddField(
            model_name='seguimientoticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='GestorITapps.ticketit'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestorITapps.edificio'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorITapps.ubicacion'),
        ),
        migrations.AddField(
            model_name='zonaedificio',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='GestorITapps.edificio'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestorITapps.zonaedificio'),
        ),
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='current_building',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='current_site',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='current_zone',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='model',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='AssetSpecification',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='assigned_by_user',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='assetevent',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetevent',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='assetevent',
            name='from_employee',
        ),
        migrations.RemoveField(
            model_name='assetevent',
            name='from_zone',
        ),
        migrations.RemoveField(
            model_name='assetevent',
            name='related_assignment',
        ),
        migrations.RemoveField(
            model_name='assetevent',
            name='related_mwo',
        ),
        migrations.RemoveField(
            model_name='assetevent',
            name='to_employee',
        ),
        migrations.RemoveField(
            model_name='assetevent',
            name='to_zone',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.RemoveField(
            model_name='maintenanceworkorder',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='maintenanceworkorder',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='maintenanceworkorder',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to_employee',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='building',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='requester_employee',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='site',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='zone',
        ),
        migrations.DeleteModel(
            name='TicketComment',
        ),
        migrations.DeleteModel(
            name='AssetCategory',
        ),
        migrations.DeleteModel(
            name='AssetModel',
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
        migrations.DeleteModel(
            name='AssetAssignment',
        ),
        migrations.DeleteModel(
            name='AssetEvent',
        ),
        migrations.DeleteModel(
            name='MaintenancePlan',
        ),
        migrations.DeleteModel(
            name='MaintenanceWorkOrder',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='TicketCategory',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
