# Generated by Django 6.0.3 on 2026-04-22 16:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorITapps', '0002_agendamantenimiento_area_asignacionequipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_bitacora', models.CharField(max_length=30, unique=True)),
                ('fecha_bitacora', models.DateTimeField(default=django.utils.timezone.now)),
                ('situacion', models.CharField(max_length=180)),
                ('descripcion_situacion', models.TextField()),
            ],
            options={
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacora',
            },
        ),
        migrations.AlterModelOptions(
            name='seguimientoticket',
            options={'verbose_name': 'Check', 'verbose_name_plural': 'Check'},
        ),
        migrations.AlterModelOptions(
            name='ticketit',
            options={'verbose_name': 'Support', 'verbose_name_plural': 'Support'},
        ),
        migrations.RemoveField(
            model_name='seguimientoticket',
            name='cambio_estado',
        ),
        migrations.RemoveField(
            model_name='seguimientoticket',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='seguimientoticket',
            name='fecha_evento',
        ),
        migrations.RemoveField(
            model_name='seguimientoticket',
            name='usuario_evento',
        ),
        migrations.RemoveField(
            model_name='ticketit',
            name='estado_ticket',
        ),
        migrations.RemoveField(
            model_name='ticketit',
            name='fecha_cierre',
        ),
        migrations.RemoveField(
            model_name='ticketit',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='ticketit',
            name='personal_solicitante',
        ),
        migrations.RemoveField(
            model_name='ticketit',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='ticketit',
            name='solucion',
        ),
        migrations.RemoveField(
            model_name='ticketit',
            name='tecnico_asignado',
        ),
        migrations.RemoveField(
            model_name='ticketit',
            name='titulo',
        ),
        migrations.AddField(
            model_name='seguimientoticket',
            name='fecha_check',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='seguimientoticket',
            name='folio_check',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='seguimientoticket',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguimientoticket',
            name='solucion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='seguimientoticket',
            name='usuario',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='seguimientoticket',
            name='ya_terminado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketit',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_support', to='GestorITapps.area'),
        ),
        migrations.AddField(
            model_name='ticketit',
            name='detalle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketit',
            name='fecha_support',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticketit',
            name='identificador_reporte',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='ticketit',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketit',
            name='otro_tipo_equipo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ticketit',
            name='requerimiento',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='ticketit',
            name='status',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('En Revision', 'En Revision'), ('En Proceso', 'En Proceso'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketit',
            name='sub_tipo_ticket',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ticketit',
            name='tipo_equipo',
            field=models.CharField(choices=[('Computadora', 'Computadora'), ('Laptop', 'Laptop'), ('Impresora', 'Impresora'), ('Telefono', 'Telefono'), ('Escaner', 'Escaner'), ('Tablet', 'Tablet'), ('Otro', 'Otro')], default='Computadora', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketit',
            name='tipo_ticket',
            field=models.CharField(choices=[('ADMINISTRACION', 'ADMINISTRACION'), ('BPCS', 'BPCS'), ('HARDWARE', 'HARDWARE'), ('HELPDESK', 'HELPDESK'), ('TELEFONIA', 'TELEFONIA'), ('SOFTWARE', 'SOFTWARE')], default='HELPDESK', max_length=30),
        ),
        migrations.AlterField(
            model_name='seguimientoticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='GestorITapps.ticketit'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_answer', models.CharField(max_length=30)),
                ('fecha_answer', models.DateTimeField(default=django.utils.timezone.now)),
                ('solucion', models.CharField(max_length=180)),
                ('descripcion_solucion', models.TextField()),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='GestorITapps.bitacora')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answer',
            },
        ),
    ]
