# Generated by Django 6.0.3 on 2026-04-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorITapps', '0003_bitacora_alter_seguimientoticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientoticket',
            name='ticket',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ticket_check',
                to='GestorITapps.ticketit',
            ),
        ),
    ]
