/*
Ticket Priority Matrix
- Define la prioridad resultante según (impact, urgency).
- Se recomienda que haya 9 filas (3x3).
*/

BEGIN;

CREATE TABLE IF NOT EXISTS ticket_priority_matrix (
  id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  impact   impact_level NOT NULL,
  urgency  urgency_level NOT NULL,
  priority priority_level NOT NULL,
  active   boolean NOT NULL DEFAULT true,
  CONSTRAINT uq_ticket_priority_matrix UNIQUE (impact, urgency)
);

COMMIT;