/*
IT Manager - Schema base
Fecha: 2026-03-31

Objetivo:
- Inventario 100% individual (cada cable = 1 asset con etiqueta)
- Ubicaciones jerárquicas: site -> building -> zone -> ...
- Tickets para portal de usuarios
- Compras con aprobaciones multinivel
- Mantenimiento preventivo/correctivo
- Plantillas y documentos generados (PDF con WeasyPrint desde Django)

Notas:
- user_id / created_by_user_id / performed_by_user_id apuntan a Django auth_user(id).
- Se usan enums PostgreSQL para consistencia (en Django se mapearían con TextChoices).
*/

BEGIN;

-- --------------------
-- ENUMS
-- --------------------
DO $$ BEGIN CREATE TYPE asset_status AS ENUM ('in_stock','assigned','in_repair','retired','lost','disposed');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE asset_condition AS ENUM ('new','good','fair','damaged');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE location_type AS ENUM ('building','zone','office','warehouse','line','rack','other');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE movement_type AS ENUM ('inbound','outbound','transfer','adjustment','disposal');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE assignment_status AS ENUM ('active','returned','lost','damaged');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE periodicity_type AS ENUM ('days','weeks','months');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE maintenance_type AS ENUM ('preventive','corrective');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE maintenance_status AS ENUM ('scheduled','in_progress','done','canceled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE priority_level AS ENUM ('low','medium','high','critical');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE ticket_status AS ENUM ('new','assigned','in_progress','waiting_user','waiting_vendor','resolved','closed','canceled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE impact_level AS ENUM ('low','medium','high');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE urgency_level AS ENUM ('low','medium','high');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE purchase_request_status AS ENUM ('draft','submitted','approved','rejected','converted_to_po');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE approval_status AS ENUM ('pending','approved','rejected');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE purchase_order_status AS ENUM ('draft','sent','partially_received','received','canceled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE template_type AS ENUM ('assignment','movement','ticket','purchase_request','purchase_order','other');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE template_engine AS ENUM ('html','docx');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE generated_document_status AS ENUM ('generated','failed');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- --------------------
-- CORE: organization & locations
-- --------------------
CREATE TABLE IF NOT EXISTS site (
  id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    text NOT NULL,
  code    text NOT NULL UNIQUE,
  active  boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS location (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id            bigint NOT NULL REFERENCES site(id),
  name              text NOT NULL,

  -- code obligatorio (reglas de formato se agregan en 03_constraints_patches.sql)
  code              text NOT NULL,

  location_type      location_type NOT NULL DEFAULT 'other',
  parent_location_id bigint NULL REFERENCES location(id) ON DELETE SET NULL,
  active            boolean NOT NULL DEFAULT true,

  -- evita duplicados de nombre en el mismo padre
  CONSTRAINT uq_location_sibling UNIQUE (site_id, parent_location_id, name)
);

-- Un código no se repite dentro de la misma sede (permite futuras sedes)
CREATE UNIQUE INDEX IF NOT EXISTS uq_location_site_code ON location(site_id, code);

CREATE INDEX IF NOT EXISTS idx_location_site ON location(site_id);
CREATE INDEX IF NOT EXISTS idx_location_parent ON location(parent_location_id);

-- --------------------
-- CORE: people
-- --------------------
CREATE TABLE IF NOT EXISTS department (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL UNIQUE,
  cost_center text NULL,
  active      boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS person (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       bigint NULL UNIQUE,   -- Django auth_user(id)
  employee_code text NULL UNIQUE,
  full_name     text NOT NULL,
  email         text NULL,
  phone         text NULL,

  department_id bigint NOT NULL REFERENCES department(id),
  site_id       bigint NOT NULL REFERENCES site(id),

  active        boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_person_department ON person(department_id);
CREATE INDEX IF NOT EXISTS idx_person_site ON person(site_id);

-- --------------------
-- INVENTORY CATALOG
-- --------------------
CREATE TABLE IF NOT EXISTS asset_category (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name               text NOT NULL UNIQUE,
  parent_category_id bigint NULL REFERENCES asset_category(id) ON DELETE SET NULL,
  active             boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_asset_category_parent ON asset_category(parent_category_id);

CREATE TABLE IF NOT EXISTS asset_brand (
  id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS asset_model (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id    bigint NOT NULL REFERENCES asset_brand(id),
  category_id bigint NOT NULL REFERENCES asset_category(id),
  name        text NOT NULL,
  specs_json  jsonb NOT NULL DEFAULT '{}'::jsonb,
  active      boolean NOT NULL DEFAULT true,
  CONSTRAINT uq_model UNIQUE (brand_id, category_id, name)
);

CREATE INDEX IF NOT EXISTS idx_asset_model_brand ON asset_model(brand_id);
CREATE INDEX IF NOT EXISTS idx_asset_model_category ON asset_model(category_id);

-- --------------------
-- PURCHASING: suppliers
-- --------------------
CREATE TABLE IF NOT EXISTS supplier (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL UNIQUE,
  rfc_tax_id   text NULL,
  contact_name text NULL,
  email        text NULL,
  phone        text NULL,
  address      text NULL,
  active       boolean NOT NULL DEFAULT true
);

-- --------------------
-- ASSET: everything is an individual asset (including cables)
-- --------------------
CREATE TABLE IF NOT EXISTS asset (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- asset_tag se autogenera (AST-YYYY-000001) con trigger en 02_folios_and_triggers.sql
  asset_tag           text NOT NULL UNIQUE,

  category_id         bigint NOT NULL REFERENCES asset_category(id),
  brand_id            bigint NULL REFERENCES asset_brand(id),
  model_id            bigint NULL REFERENCES asset_model(id),

  -- serial global unique (cuando aplica). Cables normalmente NULL.
  serial_number       text NULL UNIQUE,

  part_number         text NULL,
  name                text NULL,
  description         text NULL,

  status              asset_status NOT NULL DEFAULT 'in_stock',
  condition           asset_condition NOT NULL DEFAULT 'good',

  purchase_date       date NULL,
  warranty_end        date NULL,

  supplier_id         bigint NULL REFERENCES supplier(id),
  acquisition_doc_type text NULL,
  acquisition_doc_ref  text NULL,

  current_location_id bigint NULL REFERENCES location(id) ON DELETE SET NULL,

  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_asset_category ON asset(category_id);
CREATE INDEX IF NOT EXISTS idx_asset_status ON asset(status);
CREATE INDEX IF NOT EXISTS idx_asset_location ON asset(current_location_id);

CREATE TABLE IF NOT EXISTS asset_relation (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_asset_id bigint NOT NULL REFERENCES asset(id) ON DELETE CASCADE,
  child_asset_id  bigint NOT NULL REFERENCES asset(id) ON DELETE CASCADE,
  relation_type   text NOT NULL, -- includes/accessory/component/bundled
  start_date      date NOT NULL DEFAULT CURRENT_DATE,
  end_date        date NULL,
  notes           text NULL,
  CONSTRAINT uq_asset_relation UNIQUE (parent_asset_id, child_asset_id, relation_type, start_date)
);

-- --------------------
-- INVENTORY MOVEMENTS
-- --------------------
CREATE TABLE IF NOT EXISTS inventory_movement (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                   text NOT NULL UNIQUE, -- MOV-YYYY-000001 (trigger en 02)
  movement_type          movement_type NOT NULL,
  movement_date          timestamptz NOT NULL DEFAULT now(),

  from_location_id       bigint NULL REFERENCES location(id) ON DELETE SET NULL,
  to_location_id         bigint NULL REFERENCES location(id) ON DELETE SET NULL,

  requested_by_person_id bigint NULL REFERENCES person(id) ON DELETE SET NULL,
  approved_by_user_id    bigint NULL, -- Django auth_user(id)
  performed_by_user_id   bigint NOT NULL, -- Django auth_user(id)

  notes                  text NULL
);

CREATE INDEX IF NOT EXISTS idx_inv_mov_type ON inventory_movement(movement_type);
CREATE INDEX IF NOT EXISTS idx_inv_mov_date ON inventory_movement(movement_date);

CREATE TABLE IF NOT EXISTS inventory_movement_line (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movement_id bigint NOT NULL REFERENCES inventory_movement(id) ON DELETE CASCADE,
  asset_id    bigint NOT NULL REFERENCES asset(id),
  notes       text NULL,
  CONSTRAINT uq_movement_asset UNIQUE (movement_id, asset_id)
);

CREATE INDEX IF NOT EXISTS idx_inv_mov_line_asset ON inventory_movement_line(asset_id);

-- --------------------
-- ASSIGNMENTS (responsivas)
-- --------------------
CREATE TABLE IF NOT EXISTS asset_assignment (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_id              bigint NOT NULL REFERENCES asset(id),
  assigned_to_person_id bigint NOT NULL REFERENCES person(id),
  assigned_by_user_id   bigint NOT NULL, -- Django auth_user(id)

  assigned_date         date NOT NULL DEFAULT CURRENT_DATE,
  expected_return_date  date NULL,
  returned_date         date NULL,

  assignment_status     assignment_status NOT NULL DEFAULT 'active',
  location_id           bigint NULL REFERENCES location(id) ON DELETE SET NULL,
  notes                 text NULL
);

-- Solo una asignación activa por asset
CREATE UNIQUE INDEX IF NOT EXISTS uq_asset_one_active_assignment
ON asset_assignment(asset_id)
WHERE returned_date IS NULL;

-- --------------------
-- MAINTENANCE
-- --------------------
CREATE TABLE IF NOT EXISTS maintenance_plan (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              text NOT NULL UNIQUE,
  category_id       bigint NULL REFERENCES asset_category(id) ON DELETE SET NULL,
  periodicity_type  periodicity_type NOT NULL,
  periodicity_value int NOT NULL CHECK (periodicity_value > 0),
  active            boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS maintenance_work_order (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                 text NOT NULL UNIQUE, -- MNT-YYYY-000001 (trigger en 02)
  asset_id             bigint NOT NULL REFERENCES asset(id),
  plan_id              bigint NULL REFERENCES maintenance_plan(id) ON DELETE SET NULL,

  maintenance_type     maintenance_type NOT NULL,
  status               maintenance_status NOT NULL DEFAULT 'scheduled',
  priority             priority_level NOT NULL DEFAULT 'medium',

  opened_at            timestamptz NOT NULL DEFAULT now(),
  scheduled_for        timestamptz NULL,
  started_at           timestamptz NULL,
  completed_at         timestamptz NULL,

  technician_person_id bigint NULL REFERENCES person(id) ON DELETE SET NULL,
  created_by_user_id   bigint NOT NULL, -- Django auth_user(id)

  findings             text NULL,
  actions_taken        text NULL
);

-- --------------------
-- TICKETS (portal)
-- --------------------
CREATE TABLE IF NOT EXISTS ticket_category (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      text NOT NULL UNIQUE,
  parent_id bigint NULL REFERENCES ticket_category(id) ON DELETE SET NULL,
  active    boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS support_group (
  id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name   text NOT NULL UNIQUE,
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS ticket (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                    text NOT NULL UNIQUE, -- TCK-YYYY-000001 (trigger en 02)

  created_at              timestamptz NOT NULL DEFAULT now(),
  created_by_person_id    bigint NOT NULL REFERENCES person(id) ON DELETE RESTRICT,
  requested_for_person_id bigint NULL REFERENCES person(id) ON DELETE SET NULL,

  department_id           bigint NULL REFERENCES department(id) ON DELETE SET NULL,
  site_id                 bigint NOT NULL REFERENCES site(id),
  location_id             bigint NULL REFERENCES location(id) ON DELETE SET NULL,

  category_id             bigint NULL REFERENCES ticket_category(id) ON DELETE SET NULL,
  subject                 text NOT NULL,
  description             text NOT NULL,

  impact                  impact_level NOT NULL DEFAULT 'low',
  urgency                 urgency_level NOT NULL DEFAULT 'low',
  priority                priority_level NOT NULL DEFAULT 'low',

  status                  ticket_status NOT NULL DEFAULT 'new',

  assigned_group_id       bigint NULL REFERENCES support_group(id) ON DELETE SET NULL,
  assigned_to_person_id   bigint NULL REFERENCES person(id) ON DELETE SET NULL,

  related_asset_id        bigint NULL REFERENCES asset(id) ON DELETE SET NULL,

  resolved_at             timestamptz NULL,
  closed_at               timestamptz NULL
);

CREATE INDEX IF NOT EXISTS idx_ticket_created_at ON ticket(created_at);
CREATE INDEX IF NOT EXISTS idx_ticket_status ON ticket(status);

CREATE TABLE IF NOT EXISTS ticket_comment (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id        bigint NOT NULL REFERENCES ticket(id) ON DELETE CASCADE,
  author_person_id bigint NULL REFERENCES person(id) ON DELETE SET NULL,
  author_user_id   bigint NULL, -- Django auth_user(id)
  comment          text NOT NULL,
  is_internal      boolean NOT NULL DEFAULT false,
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ticket_status_history (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id          bigint NOT NULL REFERENCES ticket(id) ON DELETE CASCADE,
  old_status         ticket_status NOT NULL,
  new_status         ticket_status NOT NULL,
  changed_by_user_id bigint NOT NULL,
  changed_at         timestamptz NOT NULL DEFAULT now(),
  notes              text NULL
);

-- --------------------
-- PURCHASING: PR + approvals (multilevel) + PO + receipt
-- --------------------
CREATE TABLE IF NOT EXISTS purchase_request (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                   text NOT NULL UNIQUE, -- PR-YYYY-000001 (trigger en 02)

  requested_by_person_id bigint NOT NULL REFERENCES person(id),
  department_id          bigint NOT NULL REFERENCES department(id),
  site_id                bigint NOT NULL REFERENCES site(id),

  status                 purchase_request_status NOT NULL DEFAULT 'draft',
  justification          text NOT NULL,

  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS purchase_request_line (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_request_id bigint NOT NULL REFERENCES purchase_request(id) ON DELETE CASCADE,
  category_id         bigint NULL REFERENCES asset_category(id) ON DELETE SET NULL,
  description         text NOT NULL,
  quantity            numeric(12,2) NOT NULL CHECK (quantity > 0),
  estimated_unit_cost numeric(14,2) NULL CHECK (estimated_unit_cost IS NULL OR estimated_unit_cost >= 0),
  needed_by           date NULL
);

CREATE TABLE IF NOT EXISTS purchase_approval (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_request_id bigint NOT NULL REFERENCES purchase_request(id) ON DELETE CASCADE,
  step                int NOT NULL CHECK (step > 0),
  approver_person_id  bigint NOT NULL REFERENCES person(id),
  status              approval_status NOT NULL DEFAULT 'pending',
  decided_at          timestamptz NULL,
  comment             text NULL,
  CONSTRAINT uq_pr_step UNIQUE (purchase_request_id, step)
);

CREATE TABLE IF NOT EXISTS purchase_order (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                 text NOT NULL UNIQUE, -- PO-YYYY-000001 (trigger en 02)

  supplier_id          bigint NOT NULL REFERENCES supplier(id),
  purchase_request_id  bigint NULL REFERENCES purchase_request(id) ON DELETE SET NULL,

  status               purchase_order_status NOT NULL DEFAULT 'draft',
  order_date           date NOT NULL DEFAULT CURRENT_DATE,
  expected_delivery_date date NULL,

  currency             text NOT NULL DEFAULT 'MXN',
  total_amount         numeric(14,2) NULL CHECK (total_amount IS NULL OR total_amount >= 0),

  created_by_user_id   bigint NOT NULL -- Django auth_user(id)
);

CREATE TABLE IF NOT EXISTS purchase_order_line (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_order_id bigint NOT NULL REFERENCES purchase_order(id) ON DELETE CASCADE,
  category_id       bigint NULL REFERENCES asset_category(id) ON DELETE SET NULL,
  description       text NOT NULL,
  quantity          numeric(12,2) NOT NULL CHECK (quantity > 0),
  unit_price        numeric(14,2) NOT NULL CHECK (unit_price >= 0),
  tax_rate          numeric(5,2) NULL CHECK (tax_rate IS NULL OR (tax_rate >= 0 AND tax_rate <= 100))
);

CREATE TABLE IF NOT EXISTS goods_receipt (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                text NOT NULL UNIQUE, -- GR-YYYY-000001 (trigger en 02)

  purchase_order_id   bigint NULL REFERENCES purchase_order(id) ON DELETE SET NULL,
  received_at         timestamptz NOT NULL DEFAULT now(),
  received_by_user_id bigint NOT NULL, -- Django auth_user(id)
  location_id         bigint NOT NULL REFERENCES location(id),
  notes               text NULL
);

CREATE TABLE IF NOT EXISTS goods_receipt_line (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  goods_receipt_id     bigint NOT NULL REFERENCES goods_receipt(id) ON DELETE CASCADE,
  purchase_order_line_id bigint NULL REFERENCES purchase_order_line(id) ON DELETE SET NULL,
  description          text NOT NULL,
  quantity             numeric(12,2) NOT NULL CHECK (quantity > 0),
  unit_cost            numeric(14,2) NOT NULL CHECK (unit_cost >= 0)
);

-- --------------------
-- FILES + TEMPLATES + GENERATED DOCS (PDF)
-- --------------------
CREATE TABLE IF NOT EXISTS file_attachment (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uploaded_by_user_id bigint NOT NULL,
  uploaded_at         timestamptz NOT NULL DEFAULT now(),
  storage_key         text NOT NULL,
  original_name       text NOT NULL,
  mime_type           text NOT NULL,
  size_bytes          bigint NOT NULL CHECK (size_bytes >= 0)
);

CREATE TABLE IF NOT EXISTS document_template (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          text NOT NULL UNIQUE,
  name          text NOT NULL,
  template_type template_type NOT NULL,
  engine        template_engine NOT NULL DEFAULT 'html',
  template_body text NOT NULL,
  active        boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS generated_document (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id        bigint NOT NULL REFERENCES document_template(id),
  created_at         timestamptz NOT NULL DEFAULT now(),
  created_by_user_id bigint NOT NULL,
  reference_type     text NOT NULL,
  reference_id       bigint NOT NULL,
  file_attachment_id bigint NULL REFERENCES file_attachment(id) ON DELETE SET NULL,
  status             generated_document_status NOT NULL DEFAULT 'generated',
  error_message      text NULL
);

CREATE INDEX IF NOT EXISTS idx_gen_doc_ref ON generated_document(reference_type, reference_id);

COMMIT;